version: '3'

services:
  ################################
  #   Setup backend container
  ################################
  backend:
    build: ./government_up_yet
    ports:
      - 5000:5000
  ################################
  #   Setup frontend container
  ################################
  frontend:
    build: ./frontend
    expose:
      - 4000
    ports:
      - 4000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    links:
    - backend
