version: '3'

services:
  ################################
  #   Setup db container
  ################################
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - env_file
    networks:
      - backend
  ################################
  #   Setup backend container
  ################################
  backend:
    build: ./government_up_yet
    ports:
      - 5000:5000
    depends_on: 
      - db
    env_file:
      - env_file
    networks:
      - backend
  ################################
  #   Setup frontend container
  ################################
  frontend:
    build: ./frontend
    expose:
      - 4000
    ports:
      - 4000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    networks:
      - frontend
    links:
      - backend

networks:
  backend:
  frontend:

volumes:
  db-data:
