# The main ingress,

# /api traffic goes to the backend
# everything else is frontend

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    certmanager.k8s.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - api.isthegovernmentupyet.com
      - www.isthegovernmentupyet.com
      secretName: government-up-yet-tls
  rules:
      - host: api.isthegovernmentupyet.com
        http:
          paths:
          - path: /
            backend:
              serviceName: backend
              servicePort: 80
      - host: www.isthegovernmentupyet.com
        http:
          paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
